/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type RecordsAPI interface {

	/*
	DomainsDomainIdRecordsGet Retrieves all records within the given domain.

	Retrieves all records within the given domain.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param domainId Fully qualifies domain name
	@return ApiDomainsDomainIdRecordsGetRequest
	*/
	DomainsDomainIdRecordsGet(ctx context.Context, domainId string) ApiDomainsDomainIdRecordsGetRequest

	// DomainsDomainIdRecordsGetExecute executes the request
	//  @return RecordCollection
	DomainsDomainIdRecordsGetExecute(r ApiDomainsDomainIdRecordsGetRequest) (*RecordCollection, *http.Response, error)

	/*
	DomainsDomainIdRecordsPost Add record to domain.

	Add record to domain.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param domainId the UUID of the domain
	@return ApiDomainsDomainIdRecordsPostRequest
	*/
	DomainsDomainIdRecordsPost(ctx context.Context, domainId string) ApiDomainsDomainIdRecordsPostRequest

	// DomainsDomainIdRecordsPostExecute executes the request
	//  @return RecordCollection
	DomainsDomainIdRecordsPostExecute(r ApiDomainsDomainIdRecordsPostRequest) (*RecordCollection, *http.Response, error)

	/*
	DomainsDomainIdRecordsRecordIdDelete Deletes the dns record with the fully qualified domain name.

	Deletes the dns record with the fully qualified domain name.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param domainId Fully qualifies domain name
	@param recordId Fully qualifies domain name
	@return ApiDomainsDomainIdRecordsRecordIdDeleteRequest
	*/
	DomainsDomainIdRecordsRecordIdDelete(ctx context.Context, domainId string, recordId string) ApiDomainsDomainIdRecordsRecordIdDeleteRequest

	// DomainsDomainIdRecordsRecordIdDeleteExecute executes the request
	//  @return Record
	DomainsDomainIdRecordsRecordIdDeleteExecute(r ApiDomainsDomainIdRecordsRecordIdDeleteRequest) (*Record, *http.Response, error)

	/*
	DomainsDomainIdRecordsRecordIdGet Get DNS record with the fully qualified domain name.

	Get DNS record with the fully qualified domain name.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param domainId the UUID of the domain
	@param recordId the UUID of the record
	@return ApiDomainsDomainIdRecordsRecordIdGetRequest
	*/
	DomainsDomainIdRecordsRecordIdGet(ctx context.Context, domainId string, recordId string) ApiDomainsDomainIdRecordsRecordIdGetRequest

	// DomainsDomainIdRecordsRecordIdGetExecute executes the request
	//  @return Record
	DomainsDomainIdRecordsRecordIdGetExecute(r ApiDomainsDomainIdRecordsRecordIdGetRequest) (*Record, *http.Response, error)
}

// RecordsAPIService RecordsAPI service
type RecordsAPIService service

type ApiDomainsDomainIdRecordsGetRequest struct {
	ctx context.Context
	ApiService RecordsAPI
	domainId string
	fqdn *string
	offset *int32
	limit *int32
	type_ *DnsRecordType
}

// Fully qualifies domain name
func (r ApiDomainsDomainIdRecordsGetRequest) Fqdn(fqdn string) ApiDomainsDomainIdRecordsGetRequest {
	r.fqdn = &fqdn
	return r
}

// Number of items to skip
func (r ApiDomainsDomainIdRecordsGetRequest) Offset(offset int32) ApiDomainsDomainIdRecordsGetRequest {
	r.offset = &offset
	return r
}

func (r ApiDomainsDomainIdRecordsGetRequest) Limit(limit int32) ApiDomainsDomainIdRecordsGetRequest {
	r.limit = &limit
	return r
}

func (r ApiDomainsDomainIdRecordsGetRequest) Type_(type_ DnsRecordType) ApiDomainsDomainIdRecordsGetRequest {
	r.type_ = &type_
	return r
}

func (r ApiDomainsDomainIdRecordsGetRequest) Execute() (*RecordCollection, *http.Response, error) {
	return r.ApiService.DomainsDomainIdRecordsGetExecute(r)
}

/*
DomainsDomainIdRecordsGet Retrieves all records within the given domain.

Retrieves all records within the given domain.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param domainId Fully qualifies domain name
 @return ApiDomainsDomainIdRecordsGetRequest
*/
func (a *RecordsAPIService) DomainsDomainIdRecordsGet(ctx context.Context, domainId string) ApiDomainsDomainIdRecordsGetRequest {
	return ApiDomainsDomainIdRecordsGetRequest{
		ApiService: a,
		ctx: ctx,
		domainId: domainId,
	}
}

// Execute executes the request
//  @return RecordCollection
func (a *RecordsAPIService) DomainsDomainIdRecordsGetExecute(r ApiDomainsDomainIdRecordsGetRequest) (*RecordCollection, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RecordCollection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RecordsAPIService.DomainsDomainIdRecordsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/domains/{domain_id}/records"
	localVarPath = strings.Replace(localVarPath, "{"+"domain_id"+"}", url.PathEscape(parameterValueToString(r.domainId, "domainId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fqdn != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fqdn", r.fqdn, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	} else {
		var defaultValue int32 = 0
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", defaultValue, "form", "")
		r.offset = &defaultValue
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue int32 = 20
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
		r.limit = &defaultValue
	}
	if r.type_ != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "type", r.type_, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDomainsDomainIdRecordsPostRequest struct {
	ctx context.Context
	ApiService RecordsAPI
	domainId string
	recordCollection *RecordCollection
}

// The new organisation.
func (r ApiDomainsDomainIdRecordsPostRequest) RecordCollection(recordCollection RecordCollection) ApiDomainsDomainIdRecordsPostRequest {
	r.recordCollection = &recordCollection
	return r
}

func (r ApiDomainsDomainIdRecordsPostRequest) Execute() (*RecordCollection, *http.Response, error) {
	return r.ApiService.DomainsDomainIdRecordsPostExecute(r)
}

/*
DomainsDomainIdRecordsPost Add record to domain.

Add record to domain.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param domainId the UUID of the domain
 @return ApiDomainsDomainIdRecordsPostRequest
*/
func (a *RecordsAPIService) DomainsDomainIdRecordsPost(ctx context.Context, domainId string) ApiDomainsDomainIdRecordsPostRequest {
	return ApiDomainsDomainIdRecordsPostRequest{
		ApiService: a,
		ctx: ctx,
		domainId: domainId,
	}
}

// Execute executes the request
//  @return RecordCollection
func (a *RecordsAPIService) DomainsDomainIdRecordsPostExecute(r ApiDomainsDomainIdRecordsPostRequest) (*RecordCollection, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RecordCollection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RecordsAPIService.DomainsDomainIdRecordsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/domains/{domain_id}/records"
	localVarPath = strings.Replace(localVarPath, "{"+"domain_id"+"}", url.PathEscape(parameterValueToString(r.domainId, "domainId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordCollection == nil {
		return localVarReturnValue, nil, reportError("recordCollection is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.recordCollection
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v BasicError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDomainsDomainIdRecordsRecordIdDeleteRequest struct {
	ctx context.Context
	ApiService RecordsAPI
	domainId string
	recordId string
}

func (r ApiDomainsDomainIdRecordsRecordIdDeleteRequest) Execute() (*Record, *http.Response, error) {
	return r.ApiService.DomainsDomainIdRecordsRecordIdDeleteExecute(r)
}

/*
DomainsDomainIdRecordsRecordIdDelete Deletes the dns record with the fully qualified domain name.

Deletes the dns record with the fully qualified domain name.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param domainId Fully qualifies domain name
 @param recordId Fully qualifies domain name
 @return ApiDomainsDomainIdRecordsRecordIdDeleteRequest
*/
func (a *RecordsAPIService) DomainsDomainIdRecordsRecordIdDelete(ctx context.Context, domainId string, recordId string) ApiDomainsDomainIdRecordsRecordIdDeleteRequest {
	return ApiDomainsDomainIdRecordsRecordIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		domainId: domainId,
		recordId: recordId,
	}
}

// Execute executes the request
//  @return Record
func (a *RecordsAPIService) DomainsDomainIdRecordsRecordIdDeleteExecute(r ApiDomainsDomainIdRecordsRecordIdDeleteRequest) (*Record, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Record
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RecordsAPIService.DomainsDomainIdRecordsRecordIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/domains/{domain_id}/records/{record_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"domain_id"+"}", url.PathEscape(parameterValueToString(r.domainId, "domainId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"record_id"+"}", url.PathEscape(parameterValueToString(r.recordId, "recordId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v BasicError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDomainsDomainIdRecordsRecordIdGetRequest struct {
	ctx context.Context
	ApiService RecordsAPI
	domainId string
	recordId string
}

func (r ApiDomainsDomainIdRecordsRecordIdGetRequest) Execute() (*Record, *http.Response, error) {
	return r.ApiService.DomainsDomainIdRecordsRecordIdGetExecute(r)
}

/*
DomainsDomainIdRecordsRecordIdGet Get DNS record with the fully qualified domain name.

Get DNS record with the fully qualified domain name.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param domainId the UUID of the domain
 @param recordId the UUID of the record
 @return ApiDomainsDomainIdRecordsRecordIdGetRequest
*/
func (a *RecordsAPIService) DomainsDomainIdRecordsRecordIdGet(ctx context.Context, domainId string, recordId string) ApiDomainsDomainIdRecordsRecordIdGetRequest {
	return ApiDomainsDomainIdRecordsRecordIdGetRequest{
		ApiService: a,
		ctx: ctx,
		domainId: domainId,
		recordId: recordId,
	}
}

// Execute executes the request
//  @return Record
func (a *RecordsAPIService) DomainsDomainIdRecordsRecordIdGetExecute(r ApiDomainsDomainIdRecordsRecordIdGetRequest) (*Record, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Record
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RecordsAPIService.DomainsDomainIdRecordsRecordIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/domains/{domain_id}/records/{record_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"domain_id"+"}", url.PathEscape(parameterValueToString(r.domainId, "domainId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"record_id"+"}", url.PathEscape(parameterValueToString(r.recordId, "recordId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v BasicError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
