/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the MXRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MXRecord{}

// MXRecord DNS MX record defining the mail servers responsible for handling email delivery for a domain.
type MXRecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// Fully qualified domain name
	Fqdn string `json:"fqdn"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// Identifies the system, service, or user that created the DNS record. This field is used for auditing, traceability, and ownership purposes. Typical values include the name of an automation system, application, integration, or a user identifier
	Source string `json:"source"`
	// Mail server priority where lower values are preferred.
	Priority int32 `json:"priority"`
	// Mail server hostname.
	Exchange string `json:"exchange"`
	AdditionalProperties map[string]interface{}
}

type _MXRecord MXRecord

// NewMXRecord instantiates a new MXRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMXRecord(fqdn string, type_ string, source string, priority int32, exchange string) *MXRecord {
	this := MXRecord{}
	this.Fqdn = fqdn
	this.Type = type_
	this.Source = source
	this.Priority = priority
	this.Exchange = exchange
	return &this
}

// NewMXRecordWithDefaults instantiates a new MXRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMXRecordWithDefaults() *MXRecord {
	this := MXRecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MXRecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MXRecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MXRecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MXRecord) SetId(v string) {
	o.Id = &v
}

// GetFqdn returns the Fqdn field value
func (o *MXRecord) GetFqdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value
// and a boolean to check if the value has been set.
func (o *MXRecord) GetFqdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fqdn, true
}

// SetFqdn sets field value
func (o *MXRecord) SetFqdn(v string) {
	o.Fqdn = v
}

// GetType returns the Type field value
func (o *MXRecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MXRecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MXRecord) SetType(v string) {
	o.Type = v
}

// GetSource returns the Source field value
func (o *MXRecord) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *MXRecord) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *MXRecord) SetSource(v string) {
	o.Source = v
}

// GetPriority returns the Priority field value
func (o *MXRecord) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *MXRecord) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *MXRecord) SetPriority(v int32) {
	o.Priority = v
}

// GetExchange returns the Exchange field value
func (o *MXRecord) GetExchange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Exchange
}

// GetExchangeOk returns a tuple with the Exchange field value
// and a boolean to check if the value has been set.
func (o *MXRecord) GetExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exchange, true
}

// SetExchange sets field value
func (o *MXRecord) SetExchange(v string) {
	o.Exchange = v
}

func (o MXRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MXRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["fqdn"] = o.Fqdn
	toSerialize["type"] = o.Type
	toSerialize["source"] = o.Source
	toSerialize["priority"] = o.Priority
	toSerialize["exchange"] = o.Exchange

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MXRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fqdn",
		"type",
		"source",
		"priority",
		"exchange",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMXRecord := _MXRecord{}

	err = json.Unmarshal(data, &varMXRecord)

	if err != nil {
		return err
	}

	*o = MXRecord(varMXRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "fqdn")
		delete(additionalProperties, "type")
		delete(additionalProperties, "source")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "exchange")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMXRecord struct {
	value *MXRecord
	isSet bool
}

func (v NullableMXRecord) Get() *MXRecord {
	return v.value
}

func (v *NullableMXRecord) Set(val *MXRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableMXRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableMXRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMXRecord(val *MXRecord) *NullableMXRecord {
	return &NullableMXRecord{value: val, isSet: true}
}

func (v NullableMXRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMXRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


