/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CAARecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CAARecord{}

// CAARecord DNS CAA record restricting which certificate authorities may issue TLS certificates for a domain.
type CAARecord struct {
	// Flags controlling record interpretation.
	Flags int32 `json:"flags"`
	// CAA property tag defining the authorization behavior.
	Tag string `json:"tag"`
	// Certificate authority authorization value.
	Value string `json:"value"`
}

type _CAARecord CAARecord

// NewCAARecord instantiates a new CAARecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCAARecord(flags int32, tag string, value string) *CAARecord {
	this := CAARecord{}
	this.Flags = flags
	this.Tag = tag
	this.Value = value
	return &this
}

// NewCAARecordWithDefaults instantiates a new CAARecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCAARecordWithDefaults() *CAARecord {
	this := CAARecord{}
	return &this
}

// GetFlags returns the Flags field value
func (o *CAARecord) GetFlags() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value
// and a boolean to check if the value has been set.
func (o *CAARecord) GetFlagsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Flags, true
}

// SetFlags sets field value
func (o *CAARecord) SetFlags(v int32) {
	o.Flags = v
}

// GetTag returns the Tag field value
func (o *CAARecord) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *CAARecord) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *CAARecord) SetTag(v string) {
	o.Tag = v
}

// GetValue returns the Value field value
func (o *CAARecord) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CAARecord) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CAARecord) SetValue(v string) {
	o.Value = v
}

func (o CAARecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CAARecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["flags"] = o.Flags
	toSerialize["tag"] = o.Tag
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *CAARecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"flags",
		"tag",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCAARecord := _CAARecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCAARecord)

	if err != nil {
		return err
	}

	*o = CAARecord(varCAARecord)

	return err
}

type NullableCAARecord struct {
	value *CAARecord
	isSet bool
}

func (v NullableCAARecord) Get() *CAARecord {
	return v.value
}

func (v *NullableCAARecord) Set(val *CAARecord) {
	v.value = val
	v.isSet = true
}

func (v NullableCAARecord) IsSet() bool {
	return v.isSet
}

func (v *NullableCAARecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCAARecord(val *CAARecord) *NullableCAARecord {
	return &NullableCAARecord{value: val, isSet: true}
}

func (v NullableCAARecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCAARecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


