/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// Record - struct for Record
type Record struct {
	AAAARecord *AAAARecord
	ARecord *ARecord
	CAARecord *CAARecord
	CNAMERecord *CNAMERecord
	MXRecord *MXRecord
	NSRecord *NSRecord
	PTRRecord *PTRRecord
	SOARecord *SOARecord
	SRVRecord *SRVRecord
	TXTRecord *TXTRecord
}

// AAAARecordAsRecord is a convenience function that returns AAAARecord wrapped in Record
func AAAARecordAsRecord(v *AAAARecord) Record {
	return Record{
		AAAARecord: v,
	}
}

// ARecordAsRecord is a convenience function that returns ARecord wrapped in Record
func ARecordAsRecord(v *ARecord) Record {
	return Record{
		ARecord: v,
	}
}

// CAARecordAsRecord is a convenience function that returns CAARecord wrapped in Record
func CAARecordAsRecord(v *CAARecord) Record {
	return Record{
		CAARecord: v,
	}
}

// CNAMERecordAsRecord is a convenience function that returns CNAMERecord wrapped in Record
func CNAMERecordAsRecord(v *CNAMERecord) Record {
	return Record{
		CNAMERecord: v,
	}
}

// MXRecordAsRecord is a convenience function that returns MXRecord wrapped in Record
func MXRecordAsRecord(v *MXRecord) Record {
	return Record{
		MXRecord: v,
	}
}

// NSRecordAsRecord is a convenience function that returns NSRecord wrapped in Record
func NSRecordAsRecord(v *NSRecord) Record {
	return Record{
		NSRecord: v,
	}
}

// PTRRecordAsRecord is a convenience function that returns PTRRecord wrapped in Record
func PTRRecordAsRecord(v *PTRRecord) Record {
	return Record{
		PTRRecord: v,
	}
}

// SOARecordAsRecord is a convenience function that returns SOARecord wrapped in Record
func SOARecordAsRecord(v *SOARecord) Record {
	return Record{
		SOARecord: v,
	}
}

// SRVRecordAsRecord is a convenience function that returns SRVRecord wrapped in Record
func SRVRecordAsRecord(v *SRVRecord) Record {
	return Record{
		SRVRecord: v,
	}
}

// TXTRecordAsRecord is a convenience function that returns TXTRecord wrapped in Record
func TXTRecordAsRecord(v *TXTRecord) Record {
	return Record{
		TXTRecord: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Record) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'A'
	if jsonDict["type"] == "A" {
		// try to unmarshal JSON data into ARecord
		err = json.Unmarshal(data, &dst.ARecord)
		if err == nil {
			return nil // data stored in dst.ARecord, return on the first match
		} else {
			dst.ARecord = nil
			return fmt.Errorf("failed to unmarshal Record as ARecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'AAAA'
	if jsonDict["type"] == "AAAA" {
		// try to unmarshal JSON data into AAAARecord
		err = json.Unmarshal(data, &dst.AAAARecord)
		if err == nil {
			return nil // data stored in dst.AAAARecord, return on the first match
		} else {
			dst.AAAARecord = nil
			return fmt.Errorf("failed to unmarshal Record as AAAARecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'CAA'
	if jsonDict["type"] == "CAA" {
		// try to unmarshal JSON data into CAARecord
		err = json.Unmarshal(data, &dst.CAARecord)
		if err == nil {
			return nil // data stored in dst.CAARecord, return on the first match
		} else {
			dst.CAARecord = nil
			return fmt.Errorf("failed to unmarshal Record as CAARecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'CNAME'
	if jsonDict["type"] == "CNAME" {
		// try to unmarshal JSON data into CNAMERecord
		err = json.Unmarshal(data, &dst.CNAMERecord)
		if err == nil {
			return nil // data stored in dst.CNAMERecord, return on the first match
		} else {
			dst.CNAMERecord = nil
			return fmt.Errorf("failed to unmarshal Record as CNAMERecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'MX'
	if jsonDict["type"] == "MX" {
		// try to unmarshal JSON data into MXRecord
		err = json.Unmarshal(data, &dst.MXRecord)
		if err == nil {
			return nil // data stored in dst.MXRecord, return on the first match
		} else {
			dst.MXRecord = nil
			return fmt.Errorf("failed to unmarshal Record as MXRecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'NS'
	if jsonDict["type"] == "NS" {
		// try to unmarshal JSON data into NSRecord
		err = json.Unmarshal(data, &dst.NSRecord)
		if err == nil {
			return nil // data stored in dst.NSRecord, return on the first match
		} else {
			dst.NSRecord = nil
			return fmt.Errorf("failed to unmarshal Record as NSRecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'PTR'
	if jsonDict["type"] == "PTR" {
		// try to unmarshal JSON data into PTRRecord
		err = json.Unmarshal(data, &dst.PTRRecord)
		if err == nil {
			return nil // data stored in dst.PTRRecord, return on the first match
		} else {
			dst.PTRRecord = nil
			return fmt.Errorf("failed to unmarshal Record as PTRRecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'SOA'
	if jsonDict["type"] == "SOA" {
		// try to unmarshal JSON data into SOARecord
		err = json.Unmarshal(data, &dst.SOARecord)
		if err == nil {
			return nil // data stored in dst.SOARecord, return on the first match
		} else {
			dst.SOARecord = nil
			return fmt.Errorf("failed to unmarshal Record as SOARecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'SRV'
	if jsonDict["type"] == "SRV" {
		// try to unmarshal JSON data into SRVRecord
		err = json.Unmarshal(data, &dst.SRVRecord)
		if err == nil {
			return nil // data stored in dst.SRVRecord, return on the first match
		} else {
			dst.SRVRecord = nil
			return fmt.Errorf("failed to unmarshal Record as SRVRecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'TXT'
	if jsonDict["type"] == "TXT" {
		// try to unmarshal JSON data into TXTRecord
		err = json.Unmarshal(data, &dst.TXTRecord)
		if err == nil {
			return nil // data stored in dst.TXTRecord, return on the first match
		} else {
			dst.TXTRecord = nil
			return fmt.Errorf("failed to unmarshal Record as TXTRecord: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Record) MarshalJSON() ([]byte, error) {
	if src.AAAARecord != nil {
		return json.Marshal(&src.AAAARecord)
	}

	if src.ARecord != nil {
		return json.Marshal(&src.ARecord)
	}

	if src.CAARecord != nil {
		return json.Marshal(&src.CAARecord)
	}

	if src.CNAMERecord != nil {
		return json.Marshal(&src.CNAMERecord)
	}

	if src.MXRecord != nil {
		return json.Marshal(&src.MXRecord)
	}

	if src.NSRecord != nil {
		return json.Marshal(&src.NSRecord)
	}

	if src.PTRRecord != nil {
		return json.Marshal(&src.PTRRecord)
	}

	if src.SOARecord != nil {
		return json.Marshal(&src.SOARecord)
	}

	if src.SRVRecord != nil {
		return json.Marshal(&src.SRVRecord)
	}

	if src.TXTRecord != nil {
		return json.Marshal(&src.TXTRecord)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Record) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AAAARecord != nil {
		return obj.AAAARecord
	}

	if obj.ARecord != nil {
		return obj.ARecord
	}

	if obj.CAARecord != nil {
		return obj.CAARecord
	}

	if obj.CNAMERecord != nil {
		return obj.CNAMERecord
	}

	if obj.MXRecord != nil {
		return obj.MXRecord
	}

	if obj.NSRecord != nil {
		return obj.NSRecord
	}

	if obj.PTRRecord != nil {
		return obj.PTRRecord
	}

	if obj.SOARecord != nil {
		return obj.SOARecord
	}

	if obj.SRVRecord != nil {
		return obj.SRVRecord
	}

	if obj.TXTRecord != nil {
		return obj.TXTRecord
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Record) GetActualInstanceValue() (interface{}) {
	if obj.AAAARecord != nil {
		return *obj.AAAARecord
	}

	if obj.ARecord != nil {
		return *obj.ARecord
	}

	if obj.CAARecord != nil {
		return *obj.CAARecord
	}

	if obj.CNAMERecord != nil {
		return *obj.CNAMERecord
	}

	if obj.MXRecord != nil {
		return *obj.MXRecord
	}

	if obj.NSRecord != nil {
		return *obj.NSRecord
	}

	if obj.PTRRecord != nil {
		return *obj.PTRRecord
	}

	if obj.SOARecord != nil {
		return *obj.SOARecord
	}

	if obj.SRVRecord != nil {
		return *obj.SRVRecord
	}

	if obj.TXTRecord != nil {
		return *obj.TXTRecord
	}

	// all schemas are nil
	return nil
}

type NullableRecord struct {
	value *Record
	isSet bool
}

func (v NullableRecord) Get() *Record {
	return v.value
}

func (v *NullableRecord) Set(val *Record) {
	v.value = val
	v.isSet = true
}

func (v NullableRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecord(val *Record) *NullableRecord {
	return &NullableRecord{value: val, isSet: true}
}

func (v NullableRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


