/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ARecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ARecord{}

// ARecord DNS A record mapping a hostname to an IPv4 address.
type ARecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// Fully qualified domain name
	Fqdn string `json:"fqdn"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// Identifies the system, service, or user that created the DNS record. This field is used for auditing, traceability, and ownership purposes. Typical values include the name of an automation system, application, integration, or a user identifier
	Source string `json:"source"`
	// IPv4 address assigned to the hostname.
	Ipv4 string `json:"ipv4"`
	AdditionalProperties map[string]interface{}
}

type _ARecord ARecord

// NewARecord instantiates a new ARecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewARecord(fqdn string, type_ string, source string, ipv4 string) *ARecord {
	this := ARecord{}
	this.Fqdn = fqdn
	this.Type = type_
	this.Source = source
	this.Ipv4 = ipv4
	return &this
}

// NewARecordWithDefaults instantiates a new ARecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewARecordWithDefaults() *ARecord {
	this := ARecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ARecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ARecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ARecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ARecord) SetId(v string) {
	o.Id = &v
}

// GetFqdn returns the Fqdn field value
func (o *ARecord) GetFqdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value
// and a boolean to check if the value has been set.
func (o *ARecord) GetFqdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fqdn, true
}

// SetFqdn sets field value
func (o *ARecord) SetFqdn(v string) {
	o.Fqdn = v
}

// GetType returns the Type field value
func (o *ARecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ARecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ARecord) SetType(v string) {
	o.Type = v
}

// GetSource returns the Source field value
func (o *ARecord) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ARecord) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ARecord) SetSource(v string) {
	o.Source = v
}

// GetIpv4 returns the Ipv4 field value
func (o *ARecord) GetIpv4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value
// and a boolean to check if the value has been set.
func (o *ARecord) GetIpv4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv4, true
}

// SetIpv4 sets field value
func (o *ARecord) SetIpv4(v string) {
	o.Ipv4 = v
}

func (o ARecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ARecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["fqdn"] = o.Fqdn
	toSerialize["type"] = o.Type
	toSerialize["source"] = o.Source
	toSerialize["ipv4"] = o.Ipv4

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ARecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fqdn",
		"type",
		"source",
		"ipv4",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varARecord := _ARecord{}

	err = json.Unmarshal(data, &varARecord)

	if err != nil {
		return err
	}

	*o = ARecord(varARecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "fqdn")
		delete(additionalProperties, "type")
		delete(additionalProperties, "source")
		delete(additionalProperties, "ipv4")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableARecord struct {
	value *ARecord
	isSet bool
}

func (v NullableARecord) Get() *ARecord {
	return v.value
}

func (v *NullableARecord) Set(val *ARecord) {
	v.value = val
	v.isSet = true
}

func (v NullableARecord) IsSet() bool {
	return v.isSet
}

func (v *NullableARecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableARecord(val *ARecord) *NullableARecord {
	return &NullableARecord{value: val, isSet: true}
}

func (v NullableARecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableARecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


