/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the RecordCollectionOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordCollectionOutput{}

// RecordCollectionOutput struct for RecordCollectionOutput
type RecordCollectionOutput struct {
	Records []RecordOutput `json:"records"`
	AdditionalProperties map[string]interface{}
}

type _RecordCollectionOutput RecordCollectionOutput

// NewRecordCollectionOutput instantiates a new RecordCollectionOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordCollectionOutput(records []RecordOutput) *RecordCollectionOutput {
	this := RecordCollectionOutput{}
	this.Records = records
	return &this
}

// NewRecordCollectionOutputWithDefaults instantiates a new RecordCollectionOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordCollectionOutputWithDefaults() *RecordCollectionOutput {
	this := RecordCollectionOutput{}
	return &this
}

// GetRecords returns the Records field value
func (o *RecordCollectionOutput) GetRecords() []RecordOutput {
	if o == nil {
		var ret []RecordOutput
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *RecordCollectionOutput) GetRecordsOk() ([]RecordOutput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *RecordCollectionOutput) SetRecords(v []RecordOutput) {
	o.Records = v
}

func (o RecordCollectionOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordCollectionOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["records"] = o.Records

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RecordCollectionOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordCollectionOutput := _RecordCollectionOutput{}

	err = json.Unmarshal(data, &varRecordCollectionOutput)

	if err != nil {
		return err
	}

	*o = RecordCollectionOutput(varRecordCollectionOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "records")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRecordCollectionOutput struct {
	value *RecordCollectionOutput
	isSet bool
}

func (v NullableRecordCollectionOutput) Get() *RecordCollectionOutput {
	return v.value
}

func (v *NullableRecordCollectionOutput) Set(val *RecordCollectionOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordCollectionOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordCollectionOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordCollectionOutput(val *RecordCollectionOutput) *NullableRecordCollectionOutput {
	return &NullableRecordCollectionOutput{value: val, isSet: true}
}

func (v NullableRecordCollectionOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordCollectionOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


