/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the NSRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NSRecord{}

// NSRecord DNS NS record delegating authority for a DNS zone to an authoritative nameserver.
type NSRecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// Fully qualified domain name
	Fqdn string `json:"fqdn"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// Identifies the system, service, or user that created the DNS record. This field is used for auditing, traceability, and ownership purposes. Typical values include the name of an automation system, application, integration, or a user identifier
	Source string `json:"source"`
	// Authoritative nameserver hostname.
	Nameserver string `json:"nameserver"`
	AdditionalProperties map[string]interface{}
}

type _NSRecord NSRecord

// NewNSRecord instantiates a new NSRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNSRecord(fqdn string, type_ string, source string, nameserver string) *NSRecord {
	this := NSRecord{}
	this.Fqdn = fqdn
	this.Type = type_
	this.Source = source
	this.Nameserver = nameserver
	return &this
}

// NewNSRecordWithDefaults instantiates a new NSRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNSRecordWithDefaults() *NSRecord {
	this := NSRecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NSRecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NSRecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NSRecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NSRecord) SetId(v string) {
	o.Id = &v
}

// GetFqdn returns the Fqdn field value
func (o *NSRecord) GetFqdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value
// and a boolean to check if the value has been set.
func (o *NSRecord) GetFqdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fqdn, true
}

// SetFqdn sets field value
func (o *NSRecord) SetFqdn(v string) {
	o.Fqdn = v
}

// GetType returns the Type field value
func (o *NSRecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NSRecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NSRecord) SetType(v string) {
	o.Type = v
}

// GetSource returns the Source field value
func (o *NSRecord) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *NSRecord) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *NSRecord) SetSource(v string) {
	o.Source = v
}

// GetNameserver returns the Nameserver field value
func (o *NSRecord) GetNameserver() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nameserver
}

// GetNameserverOk returns a tuple with the Nameserver field value
// and a boolean to check if the value has been set.
func (o *NSRecord) GetNameserverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nameserver, true
}

// SetNameserver sets field value
func (o *NSRecord) SetNameserver(v string) {
	o.Nameserver = v
}

func (o NSRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NSRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["fqdn"] = o.Fqdn
	toSerialize["type"] = o.Type
	toSerialize["source"] = o.Source
	toSerialize["nameserver"] = o.Nameserver

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NSRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fqdn",
		"type",
		"source",
		"nameserver",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNSRecord := _NSRecord{}

	err = json.Unmarshal(data, &varNSRecord)

	if err != nil {
		return err
	}

	*o = NSRecord(varNSRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "fqdn")
		delete(additionalProperties, "type")
		delete(additionalProperties, "source")
		delete(additionalProperties, "nameserver")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNSRecord struct {
	value *NSRecord
	isSet bool
}

func (v NullableNSRecord) Get() *NSRecord {
	return v.value
}

func (v *NullableNSRecord) Set(val *NSRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableNSRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableNSRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNSRecord(val *NSRecord) *NullableNSRecord {
	return &NullableNSRecord{value: val, isSet: true}
}

func (v NullableNSRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNSRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


