/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Record - Polymorphic DNS record type resolved through the `type` discriminator.
type Record struct {
	AAAARecord *AAAARecord
	ARecord *ARecord
	CAARecord *CAARecord
	CNAMERecord *CNAMERecord
	MXRecord *MXRecord
	NSRecord *NSRecord
	PTRRecord *PTRRecord
	SOARecord *SOARecord
	SRVRecord *SRVRecord
	TXTRecord *TXTRecord
}

// AAAARecordAsRecord is a convenience function that returns AAAARecord wrapped in Record
func AAAARecordAsRecord(v *AAAARecord) Record {
	return Record{
		AAAARecord: v,
	}
}

// ARecordAsRecord is a convenience function that returns ARecord wrapped in Record
func ARecordAsRecord(v *ARecord) Record {
	return Record{
		ARecord: v,
	}
}

// CAARecordAsRecord is a convenience function that returns CAARecord wrapped in Record
func CAARecordAsRecord(v *CAARecord) Record {
	return Record{
		CAARecord: v,
	}
}

// CNAMERecordAsRecord is a convenience function that returns CNAMERecord wrapped in Record
func CNAMERecordAsRecord(v *CNAMERecord) Record {
	return Record{
		CNAMERecord: v,
	}
}

// MXRecordAsRecord is a convenience function that returns MXRecord wrapped in Record
func MXRecordAsRecord(v *MXRecord) Record {
	return Record{
		MXRecord: v,
	}
}

// NSRecordAsRecord is a convenience function that returns NSRecord wrapped in Record
func NSRecordAsRecord(v *NSRecord) Record {
	return Record{
		NSRecord: v,
	}
}

// PTRRecordAsRecord is a convenience function that returns PTRRecord wrapped in Record
func PTRRecordAsRecord(v *PTRRecord) Record {
	return Record{
		PTRRecord: v,
	}
}

// SOARecordAsRecord is a convenience function that returns SOARecord wrapped in Record
func SOARecordAsRecord(v *SOARecord) Record {
	return Record{
		SOARecord: v,
	}
}

// SRVRecordAsRecord is a convenience function that returns SRVRecord wrapped in Record
func SRVRecordAsRecord(v *SRVRecord) Record {
	return Record{
		SRVRecord: v,
	}
}

// TXTRecordAsRecord is a convenience function that returns TXTRecord wrapped in Record
func TXTRecordAsRecord(v *TXTRecord) Record {
	return Record{
		TXTRecord: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Record) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AAAARecord
	err = newStrictDecoder(data).Decode(&dst.AAAARecord)
	if err == nil {
		jsonAAAARecord, _ := json.Marshal(dst.AAAARecord)
		if string(jsonAAAARecord) == "{}" { // empty struct
			dst.AAAARecord = nil
		} else {
			if err = validator.Validate(dst.AAAARecord); err != nil {
				dst.AAAARecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.AAAARecord = nil
	}

	// try to unmarshal data into ARecord
	err = newStrictDecoder(data).Decode(&dst.ARecord)
	if err == nil {
		jsonARecord, _ := json.Marshal(dst.ARecord)
		if string(jsonARecord) == "{}" { // empty struct
			dst.ARecord = nil
		} else {
			if err = validator.Validate(dst.ARecord); err != nil {
				dst.ARecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.ARecord = nil
	}

	// try to unmarshal data into CAARecord
	err = newStrictDecoder(data).Decode(&dst.CAARecord)
	if err == nil {
		jsonCAARecord, _ := json.Marshal(dst.CAARecord)
		if string(jsonCAARecord) == "{}" { // empty struct
			dst.CAARecord = nil
		} else {
			if err = validator.Validate(dst.CAARecord); err != nil {
				dst.CAARecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.CAARecord = nil
	}

	// try to unmarshal data into CNAMERecord
	err = newStrictDecoder(data).Decode(&dst.CNAMERecord)
	if err == nil {
		jsonCNAMERecord, _ := json.Marshal(dst.CNAMERecord)
		if string(jsonCNAMERecord) == "{}" { // empty struct
			dst.CNAMERecord = nil
		} else {
			if err = validator.Validate(dst.CNAMERecord); err != nil {
				dst.CNAMERecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.CNAMERecord = nil
	}

	// try to unmarshal data into MXRecord
	err = newStrictDecoder(data).Decode(&dst.MXRecord)
	if err == nil {
		jsonMXRecord, _ := json.Marshal(dst.MXRecord)
		if string(jsonMXRecord) == "{}" { // empty struct
			dst.MXRecord = nil
		} else {
			if err = validator.Validate(dst.MXRecord); err != nil {
				dst.MXRecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.MXRecord = nil
	}

	// try to unmarshal data into NSRecord
	err = newStrictDecoder(data).Decode(&dst.NSRecord)
	if err == nil {
		jsonNSRecord, _ := json.Marshal(dst.NSRecord)
		if string(jsonNSRecord) == "{}" { // empty struct
			dst.NSRecord = nil
		} else {
			if err = validator.Validate(dst.NSRecord); err != nil {
				dst.NSRecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.NSRecord = nil
	}

	// try to unmarshal data into PTRRecord
	err = newStrictDecoder(data).Decode(&dst.PTRRecord)
	if err == nil {
		jsonPTRRecord, _ := json.Marshal(dst.PTRRecord)
		if string(jsonPTRRecord) == "{}" { // empty struct
			dst.PTRRecord = nil
		} else {
			if err = validator.Validate(dst.PTRRecord); err != nil {
				dst.PTRRecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.PTRRecord = nil
	}

	// try to unmarshal data into SOARecord
	err = newStrictDecoder(data).Decode(&dst.SOARecord)
	if err == nil {
		jsonSOARecord, _ := json.Marshal(dst.SOARecord)
		if string(jsonSOARecord) == "{}" { // empty struct
			dst.SOARecord = nil
		} else {
			if err = validator.Validate(dst.SOARecord); err != nil {
				dst.SOARecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.SOARecord = nil
	}

	// try to unmarshal data into SRVRecord
	err = newStrictDecoder(data).Decode(&dst.SRVRecord)
	if err == nil {
		jsonSRVRecord, _ := json.Marshal(dst.SRVRecord)
		if string(jsonSRVRecord) == "{}" { // empty struct
			dst.SRVRecord = nil
		} else {
			if err = validator.Validate(dst.SRVRecord); err != nil {
				dst.SRVRecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.SRVRecord = nil
	}

	// try to unmarshal data into TXTRecord
	err = newStrictDecoder(data).Decode(&dst.TXTRecord)
	if err == nil {
		jsonTXTRecord, _ := json.Marshal(dst.TXTRecord)
		if string(jsonTXTRecord) == "{}" { // empty struct
			dst.TXTRecord = nil
		} else {
			if err = validator.Validate(dst.TXTRecord); err != nil {
				dst.TXTRecord = nil
			} else {
				match++
			}
		}
	} else {
		dst.TXTRecord = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AAAARecord = nil
		dst.ARecord = nil
		dst.CAARecord = nil
		dst.CNAMERecord = nil
		dst.MXRecord = nil
		dst.NSRecord = nil
		dst.PTRRecord = nil
		dst.SOARecord = nil
		dst.SRVRecord = nil
		dst.TXTRecord = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Record)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Record)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Record) MarshalJSON() ([]byte, error) {
	if src.AAAARecord != nil {
		return json.Marshal(&src.AAAARecord)
	}

	if src.ARecord != nil {
		return json.Marshal(&src.ARecord)
	}

	if src.CAARecord != nil {
		return json.Marshal(&src.CAARecord)
	}

	if src.CNAMERecord != nil {
		return json.Marshal(&src.CNAMERecord)
	}

	if src.MXRecord != nil {
		return json.Marshal(&src.MXRecord)
	}

	if src.NSRecord != nil {
		return json.Marshal(&src.NSRecord)
	}

	if src.PTRRecord != nil {
		return json.Marshal(&src.PTRRecord)
	}

	if src.SOARecord != nil {
		return json.Marshal(&src.SOARecord)
	}

	if src.SRVRecord != nil {
		return json.Marshal(&src.SRVRecord)
	}

	if src.TXTRecord != nil {
		return json.Marshal(&src.TXTRecord)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Record) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AAAARecord != nil {
		return obj.AAAARecord
	}

	if obj.ARecord != nil {
		return obj.ARecord
	}

	if obj.CAARecord != nil {
		return obj.CAARecord
	}

	if obj.CNAMERecord != nil {
		return obj.CNAMERecord
	}

	if obj.MXRecord != nil {
		return obj.MXRecord
	}

	if obj.NSRecord != nil {
		return obj.NSRecord
	}

	if obj.PTRRecord != nil {
		return obj.PTRRecord
	}

	if obj.SOARecord != nil {
		return obj.SOARecord
	}

	if obj.SRVRecord != nil {
		return obj.SRVRecord
	}

	if obj.TXTRecord != nil {
		return obj.TXTRecord
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Record) GetActualInstanceValue() (interface{}) {
	if obj.AAAARecord != nil {
		return *obj.AAAARecord
	}

	if obj.ARecord != nil {
		return *obj.ARecord
	}

	if obj.CAARecord != nil {
		return *obj.CAARecord
	}

	if obj.CNAMERecord != nil {
		return *obj.CNAMERecord
	}

	if obj.MXRecord != nil {
		return *obj.MXRecord
	}

	if obj.NSRecord != nil {
		return *obj.NSRecord
	}

	if obj.PTRRecord != nil {
		return *obj.PTRRecord
	}

	if obj.SOARecord != nil {
		return *obj.SOARecord
	}

	if obj.SRVRecord != nil {
		return *obj.SRVRecord
	}

	if obj.TXTRecord != nil {
		return *obj.TXTRecord
	}

	// all schemas are nil
	return nil
}

type NullableRecord struct {
	value *Record
	isSet bool
}

func (v NullableRecord) Get() *Record {
	return v.value
}

func (v *NullableRecord) Set(val *Record) {
	v.value = val
	v.isSet = true
}

func (v NullableRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecord(val *Record) *NullableRecord {
	return &NullableRecord{value: val, isSet: true}
}

func (v NullableRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


