/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the PTRRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PTRRecord{}

// PTRRecord DNS PTR record used for reverse DNS lookups from IP addresses to hostnames.
type PTRRecord struct {
	Record
	// Reverse DNS hostname target.
	Pointer string `json:"pointer"`
	AdditionalProperties map[string]interface{}
}

type _PTRRecord PTRRecord

// NewPTRRecord instantiates a new PTRRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPTRRecord(pointer string, type_ string) *PTRRecord {
	this := PTRRecord{}
	this.Type = type_
	this.Pointer = pointer
	return &this
}

// NewPTRRecordWithDefaults instantiates a new PTRRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPTRRecordWithDefaults() *PTRRecord {
	this := PTRRecord{}
	return &this
}

// GetPointer returns the Pointer field value
func (o *PTRRecord) GetPointer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pointer
}

// GetPointerOk returns a tuple with the Pointer field value
// and a boolean to check if the value has been set.
func (o *PTRRecord) GetPointerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pointer, true
}

// SetPointer sets field value
func (o *PTRRecord) SetPointer(v string) {
	o.Pointer = v
}

func (o PTRRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PTRRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedRecord, errRecord := json.Marshal(o.Record)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	errRecord = json.Unmarshal([]byte(serializedRecord), &toSerialize)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	toSerialize["pointer"] = o.Pointer

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PTRRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pointer",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type PTRRecordWithoutEmbeddedStruct struct {
		// Reverse DNS hostname target.
		Pointer string `json:"pointer"`
	}

	varPTRRecordWithoutEmbeddedStruct := PTRRecordWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varPTRRecordWithoutEmbeddedStruct)
	if err == nil {
		varPTRRecord := _PTRRecord{}
		varPTRRecord.Pointer = varPTRRecordWithoutEmbeddedStruct.Pointer
		*o = PTRRecord(varPTRRecord)
	} else {
		return err
	}

	varPTRRecord := _PTRRecord{}

	err = json.Unmarshal(data, &varPTRRecord)
	if err == nil {
		o.Record = varPTRRecord.Record
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pointer")

		// remove fields from embedded structs
		reflectRecord := reflect.ValueOf(o.Record)
		for i := 0; i < reflectRecord.Type().NumField(); i++ {
			t := reflectRecord.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePTRRecord struct {
	value *PTRRecord
	isSet bool
}

func (v NullablePTRRecord) Get() *PTRRecord {
	return v.value
}

func (v *NullablePTRRecord) Set(val *PTRRecord) {
	v.value = val
	v.isSet = true
}

func (v NullablePTRRecord) IsSet() bool {
	return v.isSet
}

func (v *NullablePTRRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePTRRecord(val *PTRRecord) *NullablePTRRecord {
	return &NullablePTRRecord{value: val, isSet: true}
}

func (v NullablePTRRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePTRRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


