/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AAAARecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AAAARecord{}

// AAAARecord DNS AAAA record mapping a hostname to an IPv6 address.
type AAAARecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// DNS Time To Live in seconds.
	Ttl *int32 `json:"ttl,omitempty"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// the host associated with the ipv4.
	Host string `json:"host"`
	// IPv6 address assigned to the hostname.
	Ipv6 string `json:"ipv6"`
	AdditionalProperties map[string]interface{}
}

type _AAAARecord AAAARecord

// NewAAAARecord instantiates a new AAAARecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAAAARecord(type_ string, host string, ipv6 string) *AAAARecord {
	this := AAAARecord{}
	this.Type = type_
	this.Host = host
	this.Ipv6 = ipv6
	return &this
}

// NewAAAARecordWithDefaults instantiates a new AAAARecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAAAARecordWithDefaults() *AAAARecord {
	this := AAAARecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AAAARecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AAAARecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AAAARecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AAAARecord) SetId(v string) {
	o.Id = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *AAAARecord) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AAAARecord) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *AAAARecord) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *AAAARecord) SetTtl(v int32) {
	o.Ttl = &v
}

// GetType returns the Type field value
func (o *AAAARecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AAAARecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AAAARecord) SetType(v string) {
	o.Type = v
}

// GetHost returns the Host field value
func (o *AAAARecord) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *AAAARecord) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *AAAARecord) SetHost(v string) {
	o.Host = v
}

// GetIpv6 returns the Ipv6 field value
func (o *AAAARecord) GetIpv6() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value
// and a boolean to check if the value has been set.
func (o *AAAARecord) GetIpv6Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv6, true
}

// SetIpv6 sets field value
func (o *AAAARecord) SetIpv6(v string) {
	o.Ipv6 = v
}

func (o AAAARecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AAAARecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	toSerialize["type"] = o.Type
	toSerialize["host"] = o.Host
	toSerialize["ipv6"] = o.Ipv6

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AAAARecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"host",
		"ipv6",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAAAARecord := _AAAARecord{}

	err = json.Unmarshal(data, &varAAAARecord)

	if err != nil {
		return err
	}

	*o = AAAARecord(varAAAARecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "ttl")
		delete(additionalProperties, "type")
		delete(additionalProperties, "host")
		delete(additionalProperties, "ipv6")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAAAARecord struct {
	value *AAAARecord
	isSet bool
}

func (v NullableAAAARecord) Get() *AAAARecord {
	return v.value
}

func (v *NullableAAAARecord) Set(val *AAAARecord) {
	v.value = val
	v.isSet = true
}

func (v NullableAAAARecord) IsSet() bool {
	return v.isSet
}

func (v *NullableAAAARecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAAAARecord(val *AAAARecord) *NullableAAAARecord {
	return &NullableAAAARecord{value: val, isSet: true}
}

func (v NullableAAAARecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAAAARecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


