/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// DnsRecordType Supported DNS record types: * `A` - IPv4 address record mapping a domain to a 32-bit IPv4 address. * `AAAA` - IPv6 address record mapping a domain to a 128-bit IPv6 address. * `CNAME` - Canonical name record mapping an alias to the canonical hostname. * `MX` - Mail exchanger record defining the mail servers responsible for a domain. * `TXT` - Text record used for metadata, SPF policies, and domain verification. * `NS` - Nameserver record delegating a DNS zone to authoritative nameservers. * `SOA` - Start of authority record containing zone administration and timing information. * `SRV` - Service locator record defining hostname and port information for a service. * `PTR` - Pointer record used for reverse DNS lookups from IP address to hostname. * `CAA` - Certificate authority authorization record restricting certificate issuance. 
type DnsRecordType string

// List of DnsRecordType
const (
	DNSRECORDTYPE_A DnsRecordType = "A"
	DNSRECORDTYPE_AAAA DnsRecordType = "AAAA"
	DNSRECORDTYPE_CNAME DnsRecordType = "CNAME"
	DNSRECORDTYPE_MX DnsRecordType = "MX"
	DNSRECORDTYPE_TXT DnsRecordType = "TXT"
	DNSRECORDTYPE_NS DnsRecordType = "NS"
	DNSRECORDTYPE_SOA DnsRecordType = "SOA"
	DNSRECORDTYPE_SRV DnsRecordType = "SRV"
	DNSRECORDTYPE_PTR DnsRecordType = "PTR"
	DNSRECORDTYPE_CAA DnsRecordType = "CAA"
)

// All allowed values of DnsRecordType enum
var AllowedDnsRecordTypeEnumValues = []DnsRecordType{
	"A",
	"AAAA",
	"CNAME",
	"MX",
	"TXT",
	"NS",
	"SOA",
	"SRV",
	"PTR",
	"CAA",
}

func (v *DnsRecordType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DnsRecordType(value)
	for _, existing := range AllowedDnsRecordTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DnsRecordType", value)
}

// NewDnsRecordTypeFromValue returns a pointer to a valid DnsRecordType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDnsRecordTypeFromValue(v string) (*DnsRecordType, error) {
	ev := DnsRecordType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DnsRecordType: valid values are %v", v, AllowedDnsRecordTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DnsRecordType) IsValid() bool {
	for _, existing := range AllowedDnsRecordTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DnsRecordType value
func (v DnsRecordType) Ptr() *DnsRecordType {
	return &v
}

type NullableDnsRecordType struct {
	value *DnsRecordType
	isSet bool
}

func (v NullableDnsRecordType) Get() *DnsRecordType {
	return v.value
}

func (v *NullableDnsRecordType) Set(val *DnsRecordType) {
	v.value = val
	v.isSet = true
}

func (v NullableDnsRecordType) IsSet() bool {
	return v.isSet
}

func (v *NullableDnsRecordType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnsRecordType(val *DnsRecordType) *NullableDnsRecordType {
	return &NullableDnsRecordType{value: val, isSet: true}
}

func (v NullableDnsRecordType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnsRecordType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

