/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CNAMERecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CNAMERecord{}

// CNAMERecord DNS CNAME record mapping an alias hostname to a canonical hostname.
type CNAMERecord struct {
	Record
	// Canonical hostname target.
	CanonicalName string `json:"canonicalName"`
}

type _CNAMERecord CNAMERecord

// NewCNAMERecord instantiates a new CNAMERecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCNAMERecord(canonicalName string, type_ string) *CNAMERecord {
	this := CNAMERecord{}
	this.Type = type_
	this.CanonicalName = canonicalName
	return &this
}

// NewCNAMERecordWithDefaults instantiates a new CNAMERecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCNAMERecordWithDefaults() *CNAMERecord {
	this := CNAMERecord{}
	return &this
}

// GetCanonicalName returns the CanonicalName field value
func (o *CNAMERecord) GetCanonicalName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CanonicalName
}

// GetCanonicalNameOk returns a tuple with the CanonicalName field value
// and a boolean to check if the value has been set.
func (o *CNAMERecord) GetCanonicalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanonicalName, true
}

// SetCanonicalName sets field value
func (o *CNAMERecord) SetCanonicalName(v string) {
	o.CanonicalName = v
}

func (o CNAMERecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CNAMERecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedRecord, errRecord := json.Marshal(o.Record)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	errRecord = json.Unmarshal([]byte(serializedRecord), &toSerialize)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	toSerialize["canonicalName"] = o.CanonicalName
	return toSerialize, nil
}

func (o *CNAMERecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"canonicalName",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCNAMERecord := _CNAMERecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCNAMERecord)

	if err != nil {
		return err
	}

	*o = CNAMERecord(varCNAMERecord)

	return err
}

type NullableCNAMERecord struct {
	value *CNAMERecord
	isSet bool
}

func (v NullableCNAMERecord) Get() *CNAMERecord {
	return v.value
}

func (v *NullableCNAMERecord) Set(val *CNAMERecord) {
	v.value = val
	v.isSet = true
}

func (v NullableCNAMERecord) IsSet() bool {
	return v.isSet
}

func (v *NullableCNAMERecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCNAMERecord(val *CNAMERecord) *NullableCNAMERecord {
	return &NullableCNAMERecord{value: val, isSet: true}
}

func (v NullableCNAMERecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCNAMERecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


