/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// RecordOutput - struct for RecordOutput
type RecordOutput struct {
	AAAARecord *AAAARecord
	ARecord *ARecord
	CAARecord *CAARecord
	CNAMERecord *CNAMERecord
	MXRecord *MXRecord
	NSRecord *NSRecord
	PTRRecord *PTRRecord
	SOARecord *SOARecord
	SRVRecord *SRVRecord
	TXTRecord *TXTRecord
}

// AAAARecordAsRecordOutput is a convenience function that returns AAAARecord wrapped in RecordOutput
func AAAARecordAsRecordOutput(v *AAAARecord) RecordOutput {
	return RecordOutput{
		AAAARecord: v,
	}
}

// ARecordAsRecordOutput is a convenience function that returns ARecord wrapped in RecordOutput
func ARecordAsRecordOutput(v *ARecord) RecordOutput {
	return RecordOutput{
		ARecord: v,
	}
}

// CAARecordAsRecordOutput is a convenience function that returns CAARecord wrapped in RecordOutput
func CAARecordAsRecordOutput(v *CAARecord) RecordOutput {
	return RecordOutput{
		CAARecord: v,
	}
}

// CNAMERecordAsRecordOutput is a convenience function that returns CNAMERecord wrapped in RecordOutput
func CNAMERecordAsRecordOutput(v *CNAMERecord) RecordOutput {
	return RecordOutput{
		CNAMERecord: v,
	}
}

// MXRecordAsRecordOutput is a convenience function that returns MXRecord wrapped in RecordOutput
func MXRecordAsRecordOutput(v *MXRecord) RecordOutput {
	return RecordOutput{
		MXRecord: v,
	}
}

// NSRecordAsRecordOutput is a convenience function that returns NSRecord wrapped in RecordOutput
func NSRecordAsRecordOutput(v *NSRecord) RecordOutput {
	return RecordOutput{
		NSRecord: v,
	}
}

// PTRRecordAsRecordOutput is a convenience function that returns PTRRecord wrapped in RecordOutput
func PTRRecordAsRecordOutput(v *PTRRecord) RecordOutput {
	return RecordOutput{
		PTRRecord: v,
	}
}

// SOARecordAsRecordOutput is a convenience function that returns SOARecord wrapped in RecordOutput
func SOARecordAsRecordOutput(v *SOARecord) RecordOutput {
	return RecordOutput{
		SOARecord: v,
	}
}

// SRVRecordAsRecordOutput is a convenience function that returns SRVRecord wrapped in RecordOutput
func SRVRecordAsRecordOutput(v *SRVRecord) RecordOutput {
	return RecordOutput{
		SRVRecord: v,
	}
}

// TXTRecordAsRecordOutput is a convenience function that returns TXTRecord wrapped in RecordOutput
func TXTRecordAsRecordOutput(v *TXTRecord) RecordOutput {
	return RecordOutput{
		TXTRecord: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RecordOutput) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'A'
	if jsonDict["type"] == "A" {
		// try to unmarshal JSON data into ARecord
		err = json.Unmarshal(data, &dst.ARecord)
		if err == nil {
			return nil // data stored in dst.ARecord, return on the first match
		} else {
			dst.ARecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as ARecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'AAAA'
	if jsonDict["type"] == "AAAA" {
		// try to unmarshal JSON data into AAAARecord
		err = json.Unmarshal(data, &dst.AAAARecord)
		if err == nil {
			return nil // data stored in dst.AAAARecord, return on the first match
		} else {
			dst.AAAARecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as AAAARecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'CAA'
	if jsonDict["type"] == "CAA" {
		// try to unmarshal JSON data into CAARecord
		err = json.Unmarshal(data, &dst.CAARecord)
		if err == nil {
			return nil // data stored in dst.CAARecord, return on the first match
		} else {
			dst.CAARecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as CAARecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'CNAME'
	if jsonDict["type"] == "CNAME" {
		// try to unmarshal JSON data into CNAMERecord
		err = json.Unmarshal(data, &dst.CNAMERecord)
		if err == nil {
			return nil // data stored in dst.CNAMERecord, return on the first match
		} else {
			dst.CNAMERecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as CNAMERecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'MX'
	if jsonDict["type"] == "MX" {
		// try to unmarshal JSON data into MXRecord
		err = json.Unmarshal(data, &dst.MXRecord)
		if err == nil {
			return nil // data stored in dst.MXRecord, return on the first match
		} else {
			dst.MXRecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as MXRecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'NS'
	if jsonDict["type"] == "NS" {
		// try to unmarshal JSON data into NSRecord
		err = json.Unmarshal(data, &dst.NSRecord)
		if err == nil {
			return nil // data stored in dst.NSRecord, return on the first match
		} else {
			dst.NSRecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as NSRecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'PTR'
	if jsonDict["type"] == "PTR" {
		// try to unmarshal JSON data into PTRRecord
		err = json.Unmarshal(data, &dst.PTRRecord)
		if err == nil {
			return nil // data stored in dst.PTRRecord, return on the first match
		} else {
			dst.PTRRecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as PTRRecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'SOA'
	if jsonDict["type"] == "SOA" {
		// try to unmarshal JSON data into SOARecord
		err = json.Unmarshal(data, &dst.SOARecord)
		if err == nil {
			return nil // data stored in dst.SOARecord, return on the first match
		} else {
			dst.SOARecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as SOARecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'SRV'
	if jsonDict["type"] == "SRV" {
		// try to unmarshal JSON data into SRVRecord
		err = json.Unmarshal(data, &dst.SRVRecord)
		if err == nil {
			return nil // data stored in dst.SRVRecord, return on the first match
		} else {
			dst.SRVRecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as SRVRecord: %s", err.Error())
		}
	}

	// check if the discriminator value is 'TXT'
	if jsonDict["type"] == "TXT" {
		// try to unmarshal JSON data into TXTRecord
		err = json.Unmarshal(data, &dst.TXTRecord)
		if err == nil {
			return nil // data stored in dst.TXTRecord, return on the first match
		} else {
			dst.TXTRecord = nil
			return fmt.Errorf("failed to unmarshal RecordOutput as TXTRecord: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RecordOutput) MarshalJSON() ([]byte, error) {
	if src.AAAARecord != nil {
		return json.Marshal(&src.AAAARecord)
	}

	if src.ARecord != nil {
		return json.Marshal(&src.ARecord)
	}

	if src.CAARecord != nil {
		return json.Marshal(&src.CAARecord)
	}

	if src.CNAMERecord != nil {
		return json.Marshal(&src.CNAMERecord)
	}

	if src.MXRecord != nil {
		return json.Marshal(&src.MXRecord)
	}

	if src.NSRecord != nil {
		return json.Marshal(&src.NSRecord)
	}

	if src.PTRRecord != nil {
		return json.Marshal(&src.PTRRecord)
	}

	if src.SOARecord != nil {
		return json.Marshal(&src.SOARecord)
	}

	if src.SRVRecord != nil {
		return json.Marshal(&src.SRVRecord)
	}

	if src.TXTRecord != nil {
		return json.Marshal(&src.TXTRecord)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RecordOutput) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AAAARecord != nil {
		return obj.AAAARecord
	}

	if obj.ARecord != nil {
		return obj.ARecord
	}

	if obj.CAARecord != nil {
		return obj.CAARecord
	}

	if obj.CNAMERecord != nil {
		return obj.CNAMERecord
	}

	if obj.MXRecord != nil {
		return obj.MXRecord
	}

	if obj.NSRecord != nil {
		return obj.NSRecord
	}

	if obj.PTRRecord != nil {
		return obj.PTRRecord
	}

	if obj.SOARecord != nil {
		return obj.SOARecord
	}

	if obj.SRVRecord != nil {
		return obj.SRVRecord
	}

	if obj.TXTRecord != nil {
		return obj.TXTRecord
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RecordOutput) GetActualInstanceValue() (interface{}) {
	if obj.AAAARecord != nil {
		return *obj.AAAARecord
	}

	if obj.ARecord != nil {
		return *obj.ARecord
	}

	if obj.CAARecord != nil {
		return *obj.CAARecord
	}

	if obj.CNAMERecord != nil {
		return *obj.CNAMERecord
	}

	if obj.MXRecord != nil {
		return *obj.MXRecord
	}

	if obj.NSRecord != nil {
		return *obj.NSRecord
	}

	if obj.PTRRecord != nil {
		return *obj.PTRRecord
	}

	if obj.SOARecord != nil {
		return *obj.SOARecord
	}

	if obj.SRVRecord != nil {
		return *obj.SRVRecord
	}

	if obj.TXTRecord != nil {
		return *obj.TXTRecord
	}

	// all schemas are nil
	return nil
}

type NullableRecordOutput struct {
	value *RecordOutput
	isSet bool
}

func (v NullableRecordOutput) Get() *RecordOutput {
	return v.value
}

func (v *NullableRecordOutput) Set(val *RecordOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordOutput(val *RecordOutput) *NullableRecordOutput {
	return &NullableRecordOutput{value: val, isSet: true}
}

func (v NullableRecordOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


