/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CNAMERecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CNAMERecord{}

// CNAMERecord DNS CNAME record mapping an alias hostname to a canonical hostname.
type CNAMERecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// DNS Time To Live in seconds.
	Ttl *int32 `json:"ttl,omitempty"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// Alias hostname
	Host string `json:"host"`
	// Canonical hostname target.
	CanonicalName string `json:"canonicalName"`
	AdditionalProperties map[string]interface{}
}

type _CNAMERecord CNAMERecord

// NewCNAMERecord instantiates a new CNAMERecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCNAMERecord(type_ string, host string, canonicalName string) *CNAMERecord {
	this := CNAMERecord{}
	this.Type = type_
	this.Host = host
	this.CanonicalName = canonicalName
	return &this
}

// NewCNAMERecordWithDefaults instantiates a new CNAMERecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCNAMERecordWithDefaults() *CNAMERecord {
	this := CNAMERecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CNAMERecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CNAMERecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CNAMERecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CNAMERecord) SetId(v string) {
	o.Id = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *CNAMERecord) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CNAMERecord) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *CNAMERecord) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *CNAMERecord) SetTtl(v int32) {
	o.Ttl = &v
}

// GetType returns the Type field value
func (o *CNAMERecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CNAMERecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CNAMERecord) SetType(v string) {
	o.Type = v
}

// GetHost returns the Host field value
func (o *CNAMERecord) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *CNAMERecord) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *CNAMERecord) SetHost(v string) {
	o.Host = v
}

// GetCanonicalName returns the CanonicalName field value
func (o *CNAMERecord) GetCanonicalName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CanonicalName
}

// GetCanonicalNameOk returns a tuple with the CanonicalName field value
// and a boolean to check if the value has been set.
func (o *CNAMERecord) GetCanonicalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanonicalName, true
}

// SetCanonicalName sets field value
func (o *CNAMERecord) SetCanonicalName(v string) {
	o.CanonicalName = v
}

func (o CNAMERecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CNAMERecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	toSerialize["type"] = o.Type
	toSerialize["host"] = o.Host
	toSerialize["canonicalName"] = o.CanonicalName

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CNAMERecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"host",
		"canonicalName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCNAMERecord := _CNAMERecord{}

	err = json.Unmarshal(data, &varCNAMERecord)

	if err != nil {
		return err
	}

	*o = CNAMERecord(varCNAMERecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "ttl")
		delete(additionalProperties, "type")
		delete(additionalProperties, "host")
		delete(additionalProperties, "canonicalName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCNAMERecord struct {
	value *CNAMERecord
	isSet bool
}

func (v NullableCNAMERecord) Get() *CNAMERecord {
	return v.value
}

func (v *NullableCNAMERecord) Set(val *CNAMERecord) {
	v.value = val
	v.isSet = true
}

func (v NullableCNAMERecord) IsSet() bool {
	return v.isSet
}

func (v *NullableCNAMERecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCNAMERecord(val *CNAMERecord) *NullableCNAMERecord {
	return &NullableCNAMERecord{value: val, isSet: true}
}

func (v NullableCNAMERecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCNAMERecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


