/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SRVRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SRVRecord{}

// SRVRecord DNS SRV record defining the hostname and port for a specific service.
type SRVRecord struct {
	// Service priority where lower values are preferred.
	Priority int32 `json:"priority"`
	// Relative weight for load balancing between services with the same priority.
	Weight int32 `json:"weight"`
	// Network port exposed by the target service.
	Port int32 `json:"port"`
	// Target hostname providing the service.
	Target string `json:"target"`
}

type _SRVRecord SRVRecord

// NewSRVRecord instantiates a new SRVRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSRVRecord(priority int32, weight int32, port int32, target string) *SRVRecord {
	this := SRVRecord{}
	this.Priority = priority
	this.Weight = weight
	this.Port = port
	this.Target = target
	return &this
}

// NewSRVRecordWithDefaults instantiates a new SRVRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSRVRecordWithDefaults() *SRVRecord {
	this := SRVRecord{}
	return &this
}

// GetPriority returns the Priority field value
func (o *SRVRecord) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *SRVRecord) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *SRVRecord) SetPriority(v int32) {
	o.Priority = v
}

// GetWeight returns the Weight field value
func (o *SRVRecord) GetWeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *SRVRecord) GetWeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *SRVRecord) SetWeight(v int32) {
	o.Weight = v
}

// GetPort returns the Port field value
func (o *SRVRecord) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *SRVRecord) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *SRVRecord) SetPort(v int32) {
	o.Port = v
}

// GetTarget returns the Target field value
func (o *SRVRecord) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *SRVRecord) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *SRVRecord) SetTarget(v string) {
	o.Target = v
}

func (o SRVRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SRVRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["priority"] = o.Priority
	toSerialize["weight"] = o.Weight
	toSerialize["port"] = o.Port
	toSerialize["target"] = o.Target
	return toSerialize, nil
}

func (o *SRVRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"priority",
		"weight",
		"port",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSRVRecord := _SRVRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSRVRecord)

	if err != nil {
		return err
	}

	*o = SRVRecord(varSRVRecord)

	return err
}

type NullableSRVRecord struct {
	value *SRVRecord
	isSet bool
}

func (v NullableSRVRecord) Get() *SRVRecord {
	return v.value
}

func (v *NullableSRVRecord) Set(val *SRVRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableSRVRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableSRVRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSRVRecord(val *SRVRecord) *NullableSRVRecord {
	return &NullableSRVRecord{value: val, isSet: true}
}

func (v NullableSRVRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSRVRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


