/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TXTRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TXTRecord{}

// TXTRecord DNS TXT record used for arbitrary text-based metadata such as SPF, DKIM, and domain verification.
type TXTRecord struct {
	Record
	// TXT record value.
	Value string `json:"value"`
}

type _TXTRecord TXTRecord

// NewTXTRecord instantiates a new TXTRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTXTRecord(value string, type_ string) *TXTRecord {
	this := TXTRecord{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewTXTRecordWithDefaults instantiates a new TXTRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTXTRecordWithDefaults() *TXTRecord {
	this := TXTRecord{}
	return &this
}

// GetValue returns the Value field value
func (o *TXTRecord) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *TXTRecord) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *TXTRecord) SetValue(v string) {
	o.Value = v
}

func (o TXTRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TXTRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedRecord, errRecord := json.Marshal(o.Record)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	errRecord = json.Unmarshal([]byte(serializedRecord), &toSerialize)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *TXTRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTXTRecord := _TXTRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTXTRecord)

	if err != nil {
		return err
	}

	*o = TXTRecord(varTXTRecord)

	return err
}

type NullableTXTRecord struct {
	value *TXTRecord
	isSet bool
}

func (v NullableTXTRecord) Get() *TXTRecord {
	return v.value
}

func (v *NullableTXTRecord) Set(val *TXTRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableTXTRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableTXTRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTXTRecord(val *TXTRecord) *NullableTXTRecord {
	return &NullableTXTRecord{value: val, isSet: true}
}

func (v NullableTXTRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTXTRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


