/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the PTRRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PTRRecord{}

// PTRRecord DNS PTR record used for reverse DNS lookups from IP addresses to hostnames.
type PTRRecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// DNS Time To Live in seconds.
	Ttl *int32 `json:"ttl,omitempty"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// key/name.
	Name string `json:"name"`
	// Reverse DNS hostname target.
	Pointer string `json:"pointer"`
	AdditionalProperties map[string]interface{}
}

type _PTRRecord PTRRecord

// NewPTRRecord instantiates a new PTRRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPTRRecord(type_ string, name string, pointer string) *PTRRecord {
	this := PTRRecord{}
	this.Type = type_
	this.Name = name
	this.Pointer = pointer
	return &this
}

// NewPTRRecordWithDefaults instantiates a new PTRRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPTRRecordWithDefaults() *PTRRecord {
	this := PTRRecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PTRRecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PTRRecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PTRRecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PTRRecord) SetId(v string) {
	o.Id = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *PTRRecord) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PTRRecord) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *PTRRecord) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *PTRRecord) SetTtl(v int32) {
	o.Ttl = &v
}

// GetType returns the Type field value
func (o *PTRRecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PTRRecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PTRRecord) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *PTRRecord) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PTRRecord) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PTRRecord) SetName(v string) {
	o.Name = v
}

// GetPointer returns the Pointer field value
func (o *PTRRecord) GetPointer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pointer
}

// GetPointerOk returns a tuple with the Pointer field value
// and a boolean to check if the value has been set.
func (o *PTRRecord) GetPointerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pointer, true
}

// SetPointer sets field value
func (o *PTRRecord) SetPointer(v string) {
	o.Pointer = v
}

func (o PTRRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PTRRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["pointer"] = o.Pointer

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PTRRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"pointer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPTRRecord := _PTRRecord{}

	err = json.Unmarshal(data, &varPTRRecord)

	if err != nil {
		return err
	}

	*o = PTRRecord(varPTRRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "ttl")
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "pointer")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePTRRecord struct {
	value *PTRRecord
	isSet bool
}

func (v NullablePTRRecord) Get() *PTRRecord {
	return v.value
}

func (v *NullablePTRRecord) Set(val *PTRRecord) {
	v.value = val
	v.isSet = true
}

func (v NullablePTRRecord) IsSet() bool {
	return v.isSet
}

func (v *NullablePTRRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePTRRecord(val *PTRRecord) *NullablePTRRecord {
	return &NullablePTRRecord{value: val, isSet: true}
}

func (v NullablePTRRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePTRRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


