/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecordCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordCollection{}

// RecordCollection struct for RecordCollection
type RecordCollection struct {
	Records []Record `json:"records"`
}

type _RecordCollection RecordCollection

// NewRecordCollection instantiates a new RecordCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordCollection(records []Record) *RecordCollection {
	this := RecordCollection{}
	this.Records = records
	return &this
}

// NewRecordCollectionWithDefaults instantiates a new RecordCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordCollectionWithDefaults() *RecordCollection {
	this := RecordCollection{}
	return &this
}

// GetRecords returns the Records field value
func (o *RecordCollection) GetRecords() []Record {
	if o == nil {
		var ret []Record
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *RecordCollection) GetRecordsOk() ([]Record, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *RecordCollection) SetRecords(v []Record) {
	o.Records = v
}

func (o RecordCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["records"] = o.Records
	return toSerialize, nil
}

func (o *RecordCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordCollection := _RecordCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordCollection)

	if err != nil {
		return err
	}

	*o = RecordCollection(varRecordCollection)

	return err
}

type NullableRecordCollection struct {
	value *RecordCollection
	isSet bool
}

func (v NullableRecordCollection) Get() *RecordCollection {
	return v.value
}

func (v *NullableRecordCollection) Set(val *RecordCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordCollection(val *RecordCollection) *NullableRecordCollection {
	return &NullableRecordCollection{value: val, isSet: true}
}

func (v NullableRecordCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


