/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the BasicError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasicError{}

// BasicError Standard API error response returned when a request fails.
type BasicError struct {
	// Application-specific error code.
	ErrorCode int32 `json:"error_code"`
	// Human-readable error message.
	Error string `json:"error"`
	// Request path that caused the error.
	Path string `json:"path"`
	// HTTP status code.
	Status int32 `json:"status"`
	// HTTP status text.
	StatusText string `json:"status_text"`
	// Timestamp when the error occurred.
	Timestamp time.Time `json:"timestamp"`
	AdditionalProperties map[string]interface{}
}

type _BasicError BasicError

// NewBasicError instantiates a new BasicError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasicError(errorCode int32, error_ string, path string, status int32, statusText string, timestamp time.Time) *BasicError {
	this := BasicError{}
	this.ErrorCode = errorCode
	this.Error = error_
	this.Path = path
	this.Status = status
	this.StatusText = statusText
	this.Timestamp = timestamp
	return &this
}

// NewBasicErrorWithDefaults instantiates a new BasicError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasicErrorWithDefaults() *BasicError {
	this := BasicError{}
	return &this
}

// GetErrorCode returns the ErrorCode field value
func (o *BasicError) GetErrorCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value
// and a boolean to check if the value has been set.
func (o *BasicError) GetErrorCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorCode, true
}

// SetErrorCode sets field value
func (o *BasicError) SetErrorCode(v int32) {
	o.ErrorCode = v
}

// GetError returns the Error field value
func (o *BasicError) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *BasicError) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *BasicError) SetError(v string) {
	o.Error = v
}

// GetPath returns the Path field value
func (o *BasicError) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *BasicError) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *BasicError) SetPath(v string) {
	o.Path = v
}

// GetStatus returns the Status field value
func (o *BasicError) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BasicError) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BasicError) SetStatus(v int32) {
	o.Status = v
}

// GetStatusText returns the StatusText field value
func (o *BasicError) GetStatusText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatusText
}

// GetStatusTextOk returns a tuple with the StatusText field value
// and a boolean to check if the value has been set.
func (o *BasicError) GetStatusTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusText, true
}

// SetStatusText sets field value
func (o *BasicError) SetStatusText(v string) {
	o.StatusText = v
}

// GetTimestamp returns the Timestamp field value
func (o *BasicError) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *BasicError) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *BasicError) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o BasicError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasicError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error_code"] = o.ErrorCode
	toSerialize["error"] = o.Error
	toSerialize["path"] = o.Path
	toSerialize["status"] = o.Status
	toSerialize["status_text"] = o.StatusText
	toSerialize["timestamp"] = o.Timestamp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BasicError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error_code",
		"error",
		"path",
		"status",
		"status_text",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBasicError := _BasicError{}

	err = json.Unmarshal(data, &varBasicError)

	if err != nil {
		return err
	}

	*o = BasicError(varBasicError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error_code")
		delete(additionalProperties, "error")
		delete(additionalProperties, "path")
		delete(additionalProperties, "status")
		delete(additionalProperties, "status_text")
		delete(additionalProperties, "timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBasicError struct {
	value *BasicError
	isSet bool
}

func (v NullableBasicError) Get() *BasicError {
	return v.value
}

func (v *NullableBasicError) Set(val *BasicError) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicError) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicError(val *BasicError) *NullableBasicError {
	return &NullableBasicError{value: val, isSet: true}
}

func (v NullableBasicError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


