/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the TXTRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TXTRecord{}

// TXTRecord DNS TXT record used for arbitrary text-based metadata such as SPF, DKIM, and domain verification.
type TXTRecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// Fully qualified domain name
	Fqdn string `json:"fqdn"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// Identifies the system, service, or user that created the DNS record. This field is used for auditing, traceability, and ownership purposes. Typical values include the name of an automation system, application, integration, or a user identifier
	Source string `json:"source"`
	// TXT record value.
	Value string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _TXTRecord TXTRecord

// NewTXTRecord instantiates a new TXTRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTXTRecord(fqdn string, type_ string, source string, value string) *TXTRecord {
	this := TXTRecord{}
	this.Fqdn = fqdn
	this.Type = type_
	this.Source = source
	this.Value = value
	return &this
}

// NewTXTRecordWithDefaults instantiates a new TXTRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTXTRecordWithDefaults() *TXTRecord {
	this := TXTRecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TXTRecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TXTRecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TXTRecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TXTRecord) SetId(v string) {
	o.Id = &v
}

// GetFqdn returns the Fqdn field value
func (o *TXTRecord) GetFqdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value
// and a boolean to check if the value has been set.
func (o *TXTRecord) GetFqdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fqdn, true
}

// SetFqdn sets field value
func (o *TXTRecord) SetFqdn(v string) {
	o.Fqdn = v
}

// GetType returns the Type field value
func (o *TXTRecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TXTRecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TXTRecord) SetType(v string) {
	o.Type = v
}

// GetSource returns the Source field value
func (o *TXTRecord) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *TXTRecord) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *TXTRecord) SetSource(v string) {
	o.Source = v
}

// GetValue returns the Value field value
func (o *TXTRecord) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *TXTRecord) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *TXTRecord) SetValue(v string) {
	o.Value = v
}

func (o TXTRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TXTRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["fqdn"] = o.Fqdn
	toSerialize["type"] = o.Type
	toSerialize["source"] = o.Source
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TXTRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fqdn",
		"type",
		"source",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTXTRecord := _TXTRecord{}

	err = json.Unmarshal(data, &varTXTRecord)

	if err != nil {
		return err
	}

	*o = TXTRecord(varTXTRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "fqdn")
		delete(additionalProperties, "type")
		delete(additionalProperties, "source")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTXTRecord struct {
	value *TXTRecord
	isSet bool
}

func (v NullableTXTRecord) Get() *TXTRecord {
	return v.value
}

func (v *NullableTXTRecord) Set(val *TXTRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableTXTRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableTXTRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTXTRecord(val *TXTRecord) *NullableTXTRecord {
	return &NullableTXTRecord{value: val, isSet: true}
}

func (v NullableTXTRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTXTRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


