/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the MXRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MXRecord{}

// MXRecord DNS MX record defining the mail servers responsible for handling email delivery for a domain.
type MXRecord struct {
	Record
	// Mail server priority where lower values are preferred.
	Priority int32 `json:"priority"`
	// Mail server hostname.
	Exchange string `json:"exchange"`
	AdditionalProperties map[string]interface{}
}

type _MXRecord MXRecord

// NewMXRecord instantiates a new MXRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMXRecord(priority int32, exchange string, type_ string) *MXRecord {
	this := MXRecord{}
	this.Type = type_
	this.Priority = priority
	this.Exchange = exchange
	return &this
}

// NewMXRecordWithDefaults instantiates a new MXRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMXRecordWithDefaults() *MXRecord {
	this := MXRecord{}
	return &this
}

// GetPriority returns the Priority field value
func (o *MXRecord) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *MXRecord) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *MXRecord) SetPriority(v int32) {
	o.Priority = v
}

// GetExchange returns the Exchange field value
func (o *MXRecord) GetExchange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Exchange
}

// GetExchangeOk returns a tuple with the Exchange field value
// and a boolean to check if the value has been set.
func (o *MXRecord) GetExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exchange, true
}

// SetExchange sets field value
func (o *MXRecord) SetExchange(v string) {
	o.Exchange = v
}

func (o MXRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MXRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedRecord, errRecord := json.Marshal(o.Record)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	errRecord = json.Unmarshal([]byte(serializedRecord), &toSerialize)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	toSerialize["priority"] = o.Priority
	toSerialize["exchange"] = o.Exchange

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MXRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"priority",
		"exchange",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type MXRecordWithoutEmbeddedStruct struct {
		// Mail server priority where lower values are preferred.
		Priority int32 `json:"priority"`
		// Mail server hostname.
		Exchange string `json:"exchange"`
	}

	varMXRecordWithoutEmbeddedStruct := MXRecordWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varMXRecordWithoutEmbeddedStruct)
	if err == nil {
		varMXRecord := _MXRecord{}
		varMXRecord.Priority = varMXRecordWithoutEmbeddedStruct.Priority
		varMXRecord.Exchange = varMXRecordWithoutEmbeddedStruct.Exchange
		*o = MXRecord(varMXRecord)
	} else {
		return err
	}

	varMXRecord := _MXRecord{}

	err = json.Unmarshal(data, &varMXRecord)
	if err == nil {
		o.Record = varMXRecord.Record
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "priority")
		delete(additionalProperties, "exchange")

		// remove fields from embedded structs
		reflectRecord := reflect.ValueOf(o.Record)
		for i := 0; i < reflectRecord.Type().NumField(); i++ {
			t := reflectRecord.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMXRecord struct {
	value *MXRecord
	isSet bool
}

func (v NullableMXRecord) Get() *MXRecord {
	return v.value
}

func (v *NullableMXRecord) Set(val *MXRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableMXRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableMXRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMXRecord(val *MXRecord) *NullableMXRecord {
	return &NullableMXRecord{value: val, isSet: true}
}

func (v NullableMXRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMXRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


