/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the SOARecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SOARecord{}

// SOARecord DNS SOA record containing administrative and timing information for a DNS zone.
type SOARecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// DNS Time To Live in seconds.
	Ttl *int32 `json:"ttl,omitempty"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// Primary master nameserver for the zone.
	MName string `json:"mName"`
	// Responsible party email (encoded format).
	RName string `json:"rName"`
	Serial int32 `json:"serial"`
	Refresh int32 `json:"refresh"`
	Retry int32 `json:"retry"`
	Expire int32 `json:"expire"`
	Minimum int32 `json:"minimum"`
	AdditionalProperties map[string]interface{}
}

type _SOARecord SOARecord

// NewSOARecord instantiates a new SOARecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSOARecord(type_ string, mName string, rName string, serial int32, refresh int32, retry int32, expire int32, minimum int32) *SOARecord {
	this := SOARecord{}
	this.Type = type_
	this.MName = mName
	this.RName = rName
	this.Serial = serial
	this.Refresh = refresh
	this.Retry = retry
	this.Expire = expire
	this.Minimum = minimum
	return &this
}

// NewSOARecordWithDefaults instantiates a new SOARecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSOARecordWithDefaults() *SOARecord {
	this := SOARecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SOARecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SOARecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SOARecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SOARecord) SetId(v string) {
	o.Id = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *SOARecord) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SOARecord) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *SOARecord) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *SOARecord) SetTtl(v int32) {
	o.Ttl = &v
}

// GetType returns the Type field value
func (o *SOARecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SOARecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SOARecord) SetType(v string) {
	o.Type = v
}

// GetMName returns the MName field value
func (o *SOARecord) GetMName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MName
}

// GetMNameOk returns a tuple with the MName field value
// and a boolean to check if the value has been set.
func (o *SOARecord) GetMNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MName, true
}

// SetMName sets field value
func (o *SOARecord) SetMName(v string) {
	o.MName = v
}

// GetRName returns the RName field value
func (o *SOARecord) GetRName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RName
}

// GetRNameOk returns a tuple with the RName field value
// and a boolean to check if the value has been set.
func (o *SOARecord) GetRNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RName, true
}

// SetRName sets field value
func (o *SOARecord) SetRName(v string) {
	o.RName = v
}

// GetSerial returns the Serial field value
func (o *SOARecord) GetSerial() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Serial
}

// GetSerialOk returns a tuple with the Serial field value
// and a boolean to check if the value has been set.
func (o *SOARecord) GetSerialOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Serial, true
}

// SetSerial sets field value
func (o *SOARecord) SetSerial(v int32) {
	o.Serial = v
}

// GetRefresh returns the Refresh field value
func (o *SOARecord) GetRefresh() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Refresh
}

// GetRefreshOk returns a tuple with the Refresh field value
// and a boolean to check if the value has been set.
func (o *SOARecord) GetRefreshOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Refresh, true
}

// SetRefresh sets field value
func (o *SOARecord) SetRefresh(v int32) {
	o.Refresh = v
}

// GetRetry returns the Retry field value
func (o *SOARecord) GetRetry() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Retry
}

// GetRetryOk returns a tuple with the Retry field value
// and a boolean to check if the value has been set.
func (o *SOARecord) GetRetryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Retry, true
}

// SetRetry sets field value
func (o *SOARecord) SetRetry(v int32) {
	o.Retry = v
}

// GetExpire returns the Expire field value
func (o *SOARecord) GetExpire() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Expire
}

// GetExpireOk returns a tuple with the Expire field value
// and a boolean to check if the value has been set.
func (o *SOARecord) GetExpireOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expire, true
}

// SetExpire sets field value
func (o *SOARecord) SetExpire(v int32) {
	o.Expire = v
}

// GetMinimum returns the Minimum field value
func (o *SOARecord) GetMinimum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Minimum
}

// GetMinimumOk returns a tuple with the Minimum field value
// and a boolean to check if the value has been set.
func (o *SOARecord) GetMinimumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Minimum, true
}

// SetMinimum sets field value
func (o *SOARecord) SetMinimum(v int32) {
	o.Minimum = v
}

func (o SOARecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SOARecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	toSerialize["type"] = o.Type
	toSerialize["mName"] = o.MName
	toSerialize["rName"] = o.RName
	toSerialize["serial"] = o.Serial
	toSerialize["refresh"] = o.Refresh
	toSerialize["retry"] = o.Retry
	toSerialize["expire"] = o.Expire
	toSerialize["minimum"] = o.Minimum

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SOARecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"mName",
		"rName",
		"serial",
		"refresh",
		"retry",
		"expire",
		"minimum",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSOARecord := _SOARecord{}

	err = json.Unmarshal(data, &varSOARecord)

	if err != nil {
		return err
	}

	*o = SOARecord(varSOARecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "ttl")
		delete(additionalProperties, "type")
		delete(additionalProperties, "mName")
		delete(additionalProperties, "rName")
		delete(additionalProperties, "serial")
		delete(additionalProperties, "refresh")
		delete(additionalProperties, "retry")
		delete(additionalProperties, "expire")
		delete(additionalProperties, "minimum")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSOARecord struct {
	value *SOARecord
	isSet bool
}

func (v NullableSOARecord) Get() *SOARecord {
	return v.value
}

func (v *NullableSOARecord) Set(val *SOARecord) {
	v.value = val
	v.isSet = true
}

func (v NullableSOARecord) IsSet() bool {
	return v.isSet
}

func (v *NullableSOARecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSOARecord(val *SOARecord) *NullableSOARecord {
	return &NullableSOARecord{value: val, isSet: true}
}

func (v NullableSOARecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSOARecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


