/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the ARecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ARecord{}

// ARecord DNS A record mapping a hostname to an IPv4 address.
type ARecord struct {
	Record
	// the host associated with the ipv4.
	Host string `json:"host"`
	// IPv4 address assigned to the hostname.
	Ipv4 string `json:"ipv4"`
	AdditionalProperties map[string]interface{}
}

type _ARecord ARecord

// NewARecord instantiates a new ARecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewARecord(host string, ipv4 string, type_ string) *ARecord {
	this := ARecord{}
	this.Type = type_
	this.Host = host
	this.Ipv4 = ipv4
	return &this
}

// NewARecordWithDefaults instantiates a new ARecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewARecordWithDefaults() *ARecord {
	this := ARecord{}
	return &this
}

// GetHost returns the Host field value
func (o *ARecord) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *ARecord) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *ARecord) SetHost(v string) {
	o.Host = v
}

// GetIpv4 returns the Ipv4 field value
func (o *ARecord) GetIpv4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value
// and a boolean to check if the value has been set.
func (o *ARecord) GetIpv4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv4, true
}

// SetIpv4 sets field value
func (o *ARecord) SetIpv4(v string) {
	o.Ipv4 = v
}

func (o ARecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ARecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedRecord, errRecord := json.Marshal(o.Record)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	errRecord = json.Unmarshal([]byte(serializedRecord), &toSerialize)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	toSerialize["host"] = o.Host
	toSerialize["ipv4"] = o.Ipv4

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ARecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host",
		"ipv4",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type ARecordWithoutEmbeddedStruct struct {
		// the host associated with the ipv4.
		Host string `json:"host"`
		// IPv4 address assigned to the hostname.
		Ipv4 string `json:"ipv4"`
	}

	varARecordWithoutEmbeddedStruct := ARecordWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varARecordWithoutEmbeddedStruct)
	if err == nil {
		varARecord := _ARecord{}
		varARecord.Host = varARecordWithoutEmbeddedStruct.Host
		varARecord.Ipv4 = varARecordWithoutEmbeddedStruct.Ipv4
		*o = ARecord(varARecord)
	} else {
		return err
	}

	varARecord := _ARecord{}

	err = json.Unmarshal(data, &varARecord)
	if err == nil {
		o.Record = varARecord.Record
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "host")
		delete(additionalProperties, "ipv4")

		// remove fields from embedded structs
		reflectRecord := reflect.ValueOf(o.Record)
		for i := 0; i < reflectRecord.Type().NumField(); i++ {
			t := reflectRecord.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableARecord struct {
	value *ARecord
	isSet bool
}

func (v NullableARecord) Get() *ARecord {
	return v.value
}

func (v *NullableARecord) Set(val *ARecord) {
	v.value = val
	v.isSet = true
}

func (v NullableARecord) IsSet() bool {
	return v.isSet
}

func (v *NullableARecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableARecord(val *ARecord) *NullableARecord {
	return &NullableARecord{value: val, isSet: true}
}

func (v NullableARecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableARecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


