/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the NSRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NSRecord{}

// NSRecord DNS NS record delegating authority for a DNS zone to an authoritative nameserver.
type NSRecord struct {
	// UUID v4 associated with the DNS record.
	Id *string `json:"id,omitempty"`
	// DNS Time To Live in seconds.
	Ttl *int32 `json:"ttl,omitempty"`
	// DNS record type discriminator.
	Type string `json:"type"`
	// key/name.
	Name string `json:"name"`
	// Authoritative nameserver hostname.
	Nameserver string `json:"nameserver"`
	AdditionalProperties map[string]interface{}
}

type _NSRecord NSRecord

// NewNSRecord instantiates a new NSRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNSRecord(type_ string, name string, nameserver string) *NSRecord {
	this := NSRecord{}
	this.Type = type_
	this.Name = name
	this.Nameserver = nameserver
	return &this
}

// NewNSRecordWithDefaults instantiates a new NSRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNSRecordWithDefaults() *NSRecord {
	this := NSRecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NSRecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NSRecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NSRecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NSRecord) SetId(v string) {
	o.Id = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *NSRecord) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NSRecord) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *NSRecord) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *NSRecord) SetTtl(v int32) {
	o.Ttl = &v
}

// GetType returns the Type field value
func (o *NSRecord) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NSRecord) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NSRecord) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *NSRecord) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NSRecord) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NSRecord) SetName(v string) {
	o.Name = v
}

// GetNameserver returns the Nameserver field value
func (o *NSRecord) GetNameserver() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nameserver
}

// GetNameserverOk returns a tuple with the Nameserver field value
// and a boolean to check if the value has been set.
func (o *NSRecord) GetNameserverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nameserver, true
}

// SetNameserver sets field value
func (o *NSRecord) SetNameserver(v string) {
	o.Nameserver = v
}

func (o NSRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NSRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["nameserver"] = o.Nameserver

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NSRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"nameserver",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNSRecord := _NSRecord{}

	err = json.Unmarshal(data, &varNSRecord)

	if err != nil {
		return err
	}

	*o = NSRecord(varNSRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "ttl")
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "nameserver")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNSRecord struct {
	value *NSRecord
	isSet bool
}

func (v NullableNSRecord) Get() *NSRecord {
	return v.value
}

func (v *NullableNSRecord) Set(val *NSRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableNSRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableNSRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNSRecord(val *NSRecord) *NullableNSRecord {
	return &NullableNSRecord{value: val, isSet: true}
}

func (v NullableNSRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNSRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


