/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the NSRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NSRecord{}

// NSRecord DNS NS record delegating authority for a DNS zone to an authoritative nameserver.
type NSRecord struct {
	Record
	// Authoritative nameserver hostname.
	Nameserver string `json:"nameserver"`
	AdditionalProperties map[string]interface{}
}

type _NSRecord NSRecord

// NewNSRecord instantiates a new NSRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNSRecord(nameserver string, type_ string) *NSRecord {
	this := NSRecord{}
	this.Type = type_
	this.Nameserver = nameserver
	return &this
}

// NewNSRecordWithDefaults instantiates a new NSRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNSRecordWithDefaults() *NSRecord {
	this := NSRecord{}
	return &this
}

// GetNameserver returns the Nameserver field value
func (o *NSRecord) GetNameserver() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nameserver
}

// GetNameserverOk returns a tuple with the Nameserver field value
// and a boolean to check if the value has been set.
func (o *NSRecord) GetNameserverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nameserver, true
}

// SetNameserver sets field value
func (o *NSRecord) SetNameserver(v string) {
	o.Nameserver = v
}

func (o NSRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NSRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedRecord, errRecord := json.Marshal(o.Record)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	errRecord = json.Unmarshal([]byte(serializedRecord), &toSerialize)
	if errRecord != nil {
		return map[string]interface{}{}, errRecord
	}
	toSerialize["nameserver"] = o.Nameserver

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NSRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nameserver",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type NSRecordWithoutEmbeddedStruct struct {
		// Authoritative nameserver hostname.
		Nameserver string `json:"nameserver"`
	}

	varNSRecordWithoutEmbeddedStruct := NSRecordWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varNSRecordWithoutEmbeddedStruct)
	if err == nil {
		varNSRecord := _NSRecord{}
		varNSRecord.Nameserver = varNSRecordWithoutEmbeddedStruct.Nameserver
		*o = NSRecord(varNSRecord)
	} else {
		return err
	}

	varNSRecord := _NSRecord{}

	err = json.Unmarshal(data, &varNSRecord)
	if err == nil {
		o.Record = varNSRecord.Record
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nameserver")

		// remove fields from embedded structs
		reflectRecord := reflect.ValueOf(o.Record)
		for i := 0; i < reflectRecord.Type().NumField(); i++ {
			t := reflectRecord.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNSRecord struct {
	value *NSRecord
	isSet bool
}

func (v NullableNSRecord) Get() *NSRecord {
	return v.value
}

func (v *NullableNSRecord) Set(val *NSRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableNSRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableNSRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNSRecord(val *NSRecord) *NullableNSRecord {
	return &NullableNSRecord{value: val, isSet: true}
}

func (v NullableNSRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNSRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


