/*
DNS API

API description for DNS API.

API version: 1.0.0
Contact: development@kvalitetitsit.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dnsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AAAARecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AAAARecord{}

// AAAARecord DNS AAAA record mapping a hostname to an IPv6 address.
type AAAARecord struct {
	// the host associated with the ipv4.
	Host string `json:"host"`
	// IPv6 address assigned to the hostname.
	Ipv6 string `json:"ipv6"`
}

type _AAAARecord AAAARecord

// NewAAAARecord instantiates a new AAAARecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAAAARecord(host string, ipv6 string) *AAAARecord {
	this := AAAARecord{}
	this.Host = host
	this.Ipv6 = ipv6
	return &this
}

// NewAAAARecordWithDefaults instantiates a new AAAARecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAAAARecordWithDefaults() *AAAARecord {
	this := AAAARecord{}
	return &this
}

// GetHost returns the Host field value
func (o *AAAARecord) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *AAAARecord) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *AAAARecord) SetHost(v string) {
	o.Host = v
}

// GetIpv6 returns the Ipv6 field value
func (o *AAAARecord) GetIpv6() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value
// and a boolean to check if the value has been set.
func (o *AAAARecord) GetIpv6Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv6, true
}

// SetIpv6 sets field value
func (o *AAAARecord) SetIpv6(v string) {
	o.Ipv6 = v
}

func (o AAAARecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AAAARecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["host"] = o.Host
	toSerialize["ipv6"] = o.Ipv6
	return toSerialize, nil
}

func (o *AAAARecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host",
		"ipv6",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAAAARecord := _AAAARecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAAAARecord)

	if err != nil {
		return err
	}

	*o = AAAARecord(varAAAARecord)

	return err
}

type NullableAAAARecord struct {
	value *AAAARecord
	isSet bool
}

func (v NullableAAAARecord) Get() *AAAARecord {
	return v.value
}

func (v *NullableAAAARecord) Set(val *AAAARecord) {
	v.value = val
	v.isSet = true
}

func (v NullableAAAARecord) IsSet() bool {
	return v.isSet
}

func (v *NullableAAAARecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAAAARecord(val *AAAARecord) *NullableAAAARecord {
	return &NullableAAAARecord{value: val, isSet: true}
}

func (v NullableAAAARecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAAAARecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


